# Generated by Django 4.2.6 on 2024-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_remove_product_immagine_product_imagine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrizione',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='informazioni',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
