# Generated by Django 4.2.6 on 2024-02-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0004_preferiti_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferiti',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='preferiti',
            name='prodotto',
            field=models.ManyToManyField(to='prodotti.product'),
        ),
    ]
