# Generated by Django 4.2.6 on 2024-02-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0005_remove_preferiti_prodotto_preferiti_prodotto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferiti',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='preferiti',
            name='prodotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodotti.product'),
            preserve_default=False,
        ),
    ]
