# Generated by Django 4.2.6 on 2023-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazionecampo',
            name='durata',
            field=models.IntegerField(default=1),
        ),
    ]
