# Generated by Django 4.2.6 on 2024-02-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0002_prenotazionecampo_durata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazionecampo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
