# Generated by Django 4.2.6 on 2024-02-09 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0003_alter_prenotazionecampo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_partita', models.CharField(choices=[('Singolo', 'Singolo'), ('Doppio', 'Doppio')], max_length=10)),
                ('livello', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Esperto', 'Esperto')], max_length=20)),
                ('numero_giocatori', models.IntegerField(default=1)),
                ('pubblicata', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lobbies', to=settings.AUTH_USER_MODEL)),
                ('prenotazione_campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_lobby', to='prenotazioni.prenotazionecampo')),
            ],
        ),
    ]
