# Generated by Django 4.2.6 on 2024-02-09 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0004_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='partecipanti',
            field=models.ManyToManyField(blank=True, related_name='partecipated_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
