# Generated by Django 4.2.6 on 2024-02-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0001_initial'),
        ('carrelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordineeffettuato',
            name='id_indirizzo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impostazioni.indirizzo'),
        ),
        migrations.DeleteModel(
            name='Indirizzo',
        ),
    ]
