# Generated by Django 4.2.6 on 2024-02-08 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=50)),
                ('civico', models.CharField(max_length=50)),
                ('cap', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('stato', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
