# Generated by Django 4.2.6 on 2024-02-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='home\\static\\img'),
        ),
    ]
